### ISSUE TITLE
no new fields?

### ISSUE THREAD

**Issue by gomineko** [kaidesu/mochi-templates#1]
Vocabulary.md doesn't include Related Word, Related Reading, Related Meaning fields.

**Comment by kaidesu** [comment]
You're right! My bad, I'll get that updated tonight.

**Comment by gomineko** [comment]
> You're right! My bad, I'll get that updated tonight.

That would be cool, thank you.

**Comment by kaidesu** [comment]
Super late but got it update here:

https://github.com/kaidesu/mochi-templates/commit/4574481dfda3825dc0fc41fd6f5e53444844cd14
