### ISSUE TITLE
question

### ISSUE THREAD

**Issue by fallsdevil** [kaidesu/mochi-templates#2]
Do you have themes that can be used in the Android application?

**Comment by kaidesu** [comment]
not specifically, but as far as I know there should be no difference. If you add the theme on desktop it should sync over to mobile.

**Comment by fallsdevil** [comment]
I understand, I haven't used the desktop version yet and that's why I didn't know they were synchronized

**Comment by kaidesu** [comment]
no worries there! keep up with your studies 📖
